Ecu3.0/speedcalcfix
Tesla-UFMG/ECU pull request #17
Opened 2021-07-13 16:21 UTC by FelTell

Testado com um gerador de sinais pra simular o sensor, o gerador só permite testar valores fixos, então não foi algo "suave", mas parece ok.
Também testei com dois "sensores" com o msm sinal do gerador, o cálculo foi correto e quando tirava o sinal de apenas um ia para 0 como esperado. 
Planilha com os valores encontrados: [https://1drv.ms/x/s!Aqv49nljCrdShel3iMbKhuycHNwW9Q?e=hEP5dq](url)

2021-07-13 16:33 UTC, FelTell commented on Core/Src/speed_calc.c
> +					g_wheel_speed[i] = 0;
Aqui ele verifica a roda chamada de forma redundante. Fiz isso pra deixar o código mais simples. Talvez seja melhor tirar essa redundância.

2021-07-13 16:37 UTC, FelTell commented on Core/Src/speed_calc.c
> +					g_wheel_speed[i] = 0;
Nessas etapas de zerar a velocidade a last_messages não é modificada. Pode gerar problema na primeira interação. 
Mas acho que a maior chance é da primeira interação gerar uma velocidade muito baixa e depois corrige, nada grave.

2021-08-14 13:29 UTC, renanmoreira17 requested changes
Antes de eu avaliar, só dá uma corrigida nas indentações (principalmente de comentários), pq tá meio difícil de ler. Eu acho q tá ficando assim por causa q o eclipse tá aplicando tab no lugar de espaço pra indentar, aí buga aqui no GitHub. Dá uma olhada no "Files changed” pra vc ver como q tá.
Também, olha nesse site: https://javarevisited.blogspot.com/2016/06/how-to-make-eclipse-use-spaces-instead.html#axzz73WQQsOHI aqui ta explicando como q muda de tab pra espaço (vc ainda pode usar Tab, mas ele aplica 2 ou 4 espaços nos lugar ao invés de inserir um \t)

2021-08-14 13:45 UTC, renanmoreira17 requested changes

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Inc/speed_calc.h
> +	uint16_t pin;
mantém como speed_pin_e aqui, acho q é melhor. Aí a conversão vc faz no próprio handler de interrupção externa (o código é pequeno, então n tem problema fazer isso na interrupção)

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +speed_pin_e get_speed_pin(uint16_t pin);
igual falei lá atrás, move essa lógica pro tratamento de interrupção

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +
Vou confiar em vc q tá certo essas contas pq eu sempre gasto uma eternidade pra entender elas KKKKKK testa se tá tudo OK como esperado, se tiver, tá de boa

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +			speed_pin_e wheel_pin = get_speed_pin(message.pin);						//obtem de qual pino veio a interrupção
mesma coisa de antes

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +				Error_Handler();
pode tirar essa chamada, se precisar tratar erro, tem q tratar lá na main task

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +					g_wheel_speed[i] = 0;
Só uma dica pra essa parte: acho q tá comprometendo um pouco a legibilidade essa lógica no meio da tarefa. Faz o seguinte: cria uma função pra cada uma dessas coisas nesse arquivo mesmo, uma pra zerar caso tenha dado timeout e outra pra zerar caso uma roda tenha ficado sem msg por muito tempo, aí só chama as funções dentro do bloco do switch. Em questão de performance, vai dar na mesma, mas vc vai ganhar mt em legibilidade do código

2021-08-14 13:45 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +	}
mover pro tratamento de interrupção

2021-08-14 15:19 UTC, FelTell commented on Core/Src/speed_calc.c
> +
No dia eu fiz uma planilha e tava tudo batendo com os testes rs.

2021-08-15 20:49 UTC, renanmoreira17 requested changes

2021-08-15 20:49 UTC, renanmoreira17 commented on Core/Src/external_interrupt_handler.c
> +}
Implementa essa função em outro lugar, deixa esse arquivo só com lógica necessária de interrupção externa msm. Se vc na achar nenhum lugar válido pra implementar isso, pode criar um par de arquivos-fonte `util.h` e `util.c` pra guardar esse tipo de código

2021-08-15 20:49 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +void reset_speed_single(speed_message_t message, speed_message_t last_messages[4], uint32_t min_count);
passa essas coisas por referência, se n toda vez que vc chamar essa função ele vai fazer uma cópia das structs:
```suggestion
void reset_speed_single(speed_message_t* message, speed_message_t* last_messages, uint32_t min_count);
```

2021-08-15 20:49 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +}
Muda aqui agr q é ponteiro as coisas
```suggestion
void reset_speed_single(speed_message_t* message, speed_message_t last_messages*, uint32_t min_count){
	for(speed_pin_e i = FIRST_WHEEL; i <= LAST_WHEEL; i++)
		if((message->tim_count - last_messages[i].tim_count) > min_count)
			g_wheel_speed[i] = 0;
}
```

2021-08-15 21:56 UTC, FelTell commented
Apareceu essa info no console que n consegui resolver:
Description	Resource	Path	Location	Type
expected 'speed_message_t *' {aka 'struct <anonymous> *'} but argument is of type 'speed_message_t (*)[4]' {aka 'struct <anonymous> (*)[4]'}	speed_calc.c	/ECU/Core/Src	line 25	C/C++ Problem

2021-08-15 22:10 UTC, renanmoreira17 requested changes

2021-08-15 22:10 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +			reset_speed_single(&message, &last_messages, min_count);
`last_messages` já é um ponteiro
```suggestion
			reset_speed_single(&message, last_messages, min_count);
```

2021-08-15 22:12 UTC, renanmoreira17 commented
> Apareceu essa info no console que n consegui resolver:
> Description Resource Path Location Type
> expected 'speed_message_t _' {aka 'struct _'} but argument is of type 'speed_message_t (_)[4]' {aka 'struct (_)[4]'} speed_calc.c /ECU/Core/Src line 25 C/C++ Problem

Acho que essa mudança q eu sugeri resolve, tenta aí

2021-08-15 22:38 UTC, renanmoreira17 submitted a review, later dismissed
Conserta isso q eu pedi, se tiver compilando de boas pode dar merge

2021-08-15 22:38 UTC, renanmoreira17 commented on Core/Inc/external_interrupt_handler.h
> +#include "util.h"
move o include pro .c

2021-08-15 22:41 UTC, FelTell commented on Core/Inc/external_interrupt_handler.h
> +#include "util.h"
todos os includes ou só o util.h?

2021-08-15 22:42 UTC, renanmoreira17 commented on Core/Inc/external_interrupt_handler.h
> +#include "util.h"
se vc conseguir mover os outros tbm e conseguir compilar, pode mover tudo

2021-08-15 22:48 UTC, FelTell commented
Fiz algo errado, aprova ai denovo rs

2021-08-15 22:49 UTC, renanmoreira17 approved these changes

2021-08-15 22:56 UTC, merged