Arquivos PID.h e PID.c adicionados.
Tesla-UFMG/ECU pull request #20
Opened 2021-08-13 23:24 UTC by luizaaraujo1

2021-08-14 14:49 UTC, renanmoreira17 requested changes
Só precisa mudar o nome do diretório. Mas só queria entender uma coisa: vc pretende usar esse diretório Controles Dinâmicos pra mais coisas? Tipo colocar os códigos de controle de arrancada e vetorização neles? Se ss, OK. Se n, não precisa criar ele só pra colocar os arquivos de PID. Se for só pra colocar os arquivos do PID, pode criar o diretório PID mesmo, e lá vc coloca o PID.h e PID.c
Caso vc queria colocar outras coisas, eu sugiro vc mudar o nome pra inglês (eu sei q tá meio misturado o código com coisa em inglês e português, mas a ideia é ficar tudo em inglês no final das contas). Também, precisa ficar no padrão de nomeação q a gnt usa:

- Em CamelCase: ControlesDinamicos
- Ou snake_case: controles_dinamicos

recomendo o primeiro (mas coloca em inglês msm assim)

2021-08-18 00:11 UTC, luizaaraujo1 commented
A ideia é usar o diretório também para os códigos de controle de arrancada e vetorização.

2021-08-18 00:24 UTC, renanmoreira17 requested changes

2021-08-18 00:24 UTC, renanmoreira17 commented on Core/Inc/Controles_Dinamicos/PID.h
> +#endif /* PID_H_ */
deleta esse arquivo

2021-08-18 00:24 UTC, renanmoreira17 commented on Core/Src/Controles_Dinamicos/PID.c
> +}
deleta esse também

2021-08-18 00:24 UTC, renanmoreira17 commented on Core/Src/Controles_Dinamicos/PID.c
> +}
a compilação tá falhando justamente por causa dele

2021-08-18 00:24 UTC, renanmoreira17 commented on Core/Src/DynamicControls/PID.c
> +#include <DynamicControls/PID.h>
```suggestion
#include "DynamicControls/PID.h"
```
usa <> só pra includes de bibliotecas standard, tipo <stdio.h>, etc

2021-08-18 01:16 UTC, renanmoreira17 requested changes
Pode consertar os erros sugeridos pelo bot tbm, n tem problema editar esse arquivo e ele ficar diferente do original n
E uma coisa: quando abrir uma Conversation e vc resolver ela no commit, clica em “Resolve Conversation”. Dessa vez eu resolvi por vc, mas nas próximas vc msm pode resolver, aí se a soluação n ficar clara eu abro de novo. Precisa resolver todas as Conversations pra liberar o merge

2021-08-18 01:49 UTC, luizaaraujo1 commented
Beleza, obrigada!

2021-08-18 01:55 UTC, renanmoreira17 approved these changes

2021-08-18 02:01 UTC, merged