Ecu3.0/main taskfix.1
Tesla-UFMG/ECU pull request #31
Opened 2021-09-14 22:41 UTC by FelTell

Conserto de erro em que a ECU poderia requisitar um pequeno valor de torque para o inversor quando erros de BSE e APPS estivessem presentes ao mesmo tempo.

2021-09-14 23:08 UTC, renanmoreira17 requested changes

2021-09-14 23:08 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        apps2_percentage = 0;
dá pra simplificar essa lógica usando early-return. Ao inves de star esse valor numa variável e dps retornar ela, vc pode retornar a variável de uma vez:
```cpp
uint16_t calculate_apps2(uint16_t APPS2) {
      if (APPS2 < 260)
          return 0;
      } else if (APPS2 >= 260 && APPS2 < 467) {
          return 1.162 * APPS2 - 342.9;
etc....
```

2021-09-14 23:08 UTC, renanmoreira17 commented on Core/Src/throttle.c
>  }
mesma coisa do anterior, usa early-return

2021-09-14 23:08 UTC, renanmoreira17 commented on Core/Src/throttle.c
>  bool check_for_BSE_errors() {
pra facilitar o entendimento dessa função (pra saber mais claramente qual valor booleano ele deveria retornar caso de fato tenha um erro), muda o nome dela pra algo tipo “is_there_BSE_error” ou similar. Aí fica claro: se retornou `true`, é pq tem erro. Muda essas e todas as outras aplicáveis (tipo a de APPS, etc)

2021-09-14 23:08 UTC, renanmoreira17 commented on Core/Src/throttle_control.c
>          //se o pedal está disponível atualiza o valor de throttle_percent para o da mensagem, caso não atualiza para 0
melhora esse comentário pro comportamento exato q tem agr

2021-09-14 23:08 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        return (apps2_throttle_percent >= APPS_05_PERCENT);                         //Regulamento: EV.5.7.2
coloca o ano do regulamento q vc pegou essa regra (lembra q o regulamento de vez em quando muda a numeração dos tópicos quando passa de ano)

2021-09-14 23:09 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        return (apps2_throttle_percent >= APPS_05_PERCENT);                         //Regulamento: EV.5.7.2
aq e em todos os lugares q vc citou regulamento

2021-09-15 01:45 UTC, FelTell commented on Core/Src/throttle.c
> +        apps2_percentage = 0;
nesse caso tem um `if (apps2_percentage > 1000)` e não conseguiria só com return.

2021-09-15 02:01 UTC, FelTell commented on Core/Src/main_task.c
>  		osEventFlagsWait(ECU_control_event_id, RTD_FLAG, osFlagsNoClear, osWaitForever);
muda a `get_individual_flag()` pra esse RTOS_util tbm?

2021-09-15 02:17 UTC, FelTell commented on Core/Src/main_task.c
>  		osEventFlagsWait(ECU_control_event_id, RTD_FLAG, osFlagsNoClear, osWaitForever);
não gostei de como ficou :/
fiz um commit com a função se quiser ver, mas removi no ultimo commit
achei que acaba escondendo informações importantes tipo o timeout e parametros do wait. acho que usando `osEventFlagsWait` fica mais claro o que está acontecendo

2021-09-15 14:17 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        apps2_percentage = 0;
ah, vdd, teria como resolver com um `max(1000, conta)` no ultimo if, mas acho q n vale a pena

2021-09-15 14:32 UTC, renanmoreira17 commented on Core/Src/main_task.c
>  		osEventFlagsWait(ECU_control_event_id, RTD_FLAG, osFlagsNoClear, osWaitForever);
entao, eu pensei em usar essa função pq essas informações sao meio redundantes, e toda vez q for esperar pelo RTD precisa fornecer exatamente a mesma coisa. A questao era q o nome da função deixa claro o q ela faz: espera pelo RTD. Se a pessoa quiser saber como q a funçao faz isso, é só ela dar ctrl click e abrir a definição da função. Eu acho uma boa ideia criar a função pq se n vai ter q ficar copiando e colando esse código toda hora q quiser esperar pelo RTD, e funçoes servem justamente pra evitar isso rs (além de encapsular o comportamento com um nome mais autoexplicativo). Além de q, se precisar mudar alguma coisa no código de esperar por RTD, vai ter q mudar manualmente em todos os lugares q esperam por ele um a um. Mas vc q sabe, eu recomendo criar, mas se n quiser n tem problema tbm (mas se vc n criar, deixa um comentário em cima de cada lugar q vc faz isso explicando o q essa chamada do osEventFlagWait ta fazendo)

2021-09-15 14:35 UTC, renanmoreira17 requested changes
Sobre o comentário q deixei na Conversation: ou volta com a função do RTD ou comenta em cada lugar q espera RTD o q ta sendo exatamente feito

2021-09-17 01:41 UTC, FelTell commented on Core/Src/main_task.c
>  		osEventFlagsWait(ECU_control_event_id, RTD_FLAG, osFlagsNoClear, osWaitForever);
No momento esse osEventFlagWait por RTD só tem na main_task. Vou manter e apenas comentar. Entendo que ficaria mais intuitivo, mas ali embaixo já tem osThreadFlagsWait e só estaria usando a função em um só lugar.

2021-09-17 17:55 UTC, renanmoreira17 approved these changes

2021-09-17 22:30 UTC, merged