Criando Message Queues de 1 elemento para substituir variáveis globais
Tesla-UFMG/ECU pull request #32
Opened 2021-09-15 19:44 UTC by renanmoreira17

Como discutido anteriormente, esse patch substitui as variáveis globais por queue de 1 elemento. Isso possibilita a sincronização automática dos dados sem precisar se preocupar com semáforos/mutexes. 

Foi feito de maneira a simplificar tanto o registro de novas variáveis globais quanto o uso. Para registrar, em `Core/Inc/CMSIS_extra/global_variables_handler.h`, deve-se seguir o padrão presente lá, criando um `typedef`, um valor default e registrando no `enum`. O requisito é: 
- escolha um nome para a variável. 
- Registre esse nome exatamente nos enums. 
- Adicione o sufixo `_t` nesse nome para criar o `typedef`. 
- Adicione o sufixo `_DEFAULT_VALUE` para criar o valor padrão.
Agora, em `Core/Src/CMSIS_extra/global_variables_handler.c`:
- Na função `void global_variables_init()`, siga o padrão para registrar a queue. O nome passado como argumento para a macro deve ser exatamente igual ao nome base, que foi registrado no `enum` (essa parte é essencial, porque depende-se dela para que a macro funcione).

Para utilizar as variáveis globais, há 2 formas.
- Usando as funções criadas:
   Para utilizar as variáveis com as funções criadas, é necessário criar uma instância da variável primeiro. Exemplo:
```cpp
THROTTLE_PERCENT_t throttle_percent;
get_global_var(THROTTLE_PERCENT, &throttle_percent);
// o valor da porcentagem do pedal, no momento em que se rodou a função acima, vai estar guardado na variável throttle_percent
throttle_percent = 0;
set_global_var(THROTTLE_PERCENT, &throttle_percent);
// agora throttle percent está zerado. Se outra tarefa executar um get_global_var depois desse ponto, receberá 0.
```
- Usando as macros:
   Para utilizar as variáveis com as macros criadas, **não** é necessário criar uma instância da variável primeiro. Exemplo:
```cpp
THROTTLE_PERCENT_t throttle_percent = get_global_var_value(THROTTLE_PERCENT);
// o valor da porcentagem do pedal, no momento em que se rodou a função acima, vai estar guardado na variável throttle_percent.
// seta o valor de porcentagem para 1% acima do lido e guardado em throttle_percent
set_global_var_value(THROTTLE_PERCENT, throttle_percent + 10);
// também pode-se colocar o valor diretamente:
set_global_var_value(THROTTLE_PERCENT, 0);
```
**Mas atenção**: deve-se lembra que essas são macros, não funções. Isso quer dizer que nem sempre funcionarão do jeito esperado, já que macros são basicamente `#defines` que aceitam argumentos para moldar as substituições.

2021-09-17 01:23 UTC, FelTell requested changes
Fiz uns testes aqui com a placa e os sensores que tinha, deu pra testar modo.c, rtd.c e steering.c. Tudo funcionou perfeitamente. Ficou muito chique esse código com queue, parte mais geral do código ficou bem fácil de entender. Mas acho que pode explicar um pouco o que vc faz pra funcionar as queue, pq no momento to só aceitando rs, e eu e a glr de controle é curiosa e vai querer entender certinho.

2021-09-17 01:23 UTC, FelTell commented on Core/Inc/CMSIS_extra/global_variables_handler.h
> +    })
essas funções são pra não precisar instaciar as váriaveis né?
acho que poderia comentar para explicar um pouco melhor

2021-09-17 01:23 UTC, FelTell commented on Core/Src/CMSIS_extra/cmsis_extra.c
> +#define IS_IRQ()                  IS_IRQ_MODE()
Pra que serve isso?

2021-09-17 01:23 UTC, FelTell commented on Core/Src/CMSIS_extra/global_variables_handler.c
> +    osMessageQueuePut(var_name##_info->id, &var_name##_msg, 0, 0);
isso é para criar uma queue sem usar o cube? Comenta a função dela.
Esse trem de define pra fazer umas funções entendo nada rs

2021-09-17 12:28 UTC, luizaaraujo1 commented on Core/Src/RTD.c
> +    set_rgb_led(selected_mode.cor, FIXED);
Por que nao faz o set_rgb_led (linha 65 a 67) como o da linha 47? Pra ficar mais enxuto

2021-09-17 12:28 UTC, luizaaraujo1 commented on Core/Src/modo.c
> +            set_rgb_led(selected_mode.cor, BLINK200);
Voce nao da get_global pro selected_mode hora nenhuma. Ta certo isso?

2021-09-17 12:28 UTC, luizaaraujo1 commented on Core/Src/throttle_control.c
> +        }
Por que precisa desses { } ? (linha 28,30,32,34)

2021-09-17 12:29 UTC, luizaaraujo1 commented
> Fiz uns testes aqui com a placa e os sensores que tinha, deu pra testar modo.c, rtd.c e steering.c. Tudo funcionou perfeitamente. Ficou muito chique esse código com queue, parte mais geral do código ficou bem fácil de entender. Mas acho que pode explicar um pouco o que vc faz pra funcionar as queue, pq no momento to só aceitando rs, e eu e a glr de controle é curiosa e vai querer entender certinho.

Concordo, ficou lindo.

2021-09-18 14:42 UTC, renanmoreira17 commented on Core/Src/CMSIS_extra/cmsis_extra.c
> +#define IS_IRQ()                  IS_IRQ_MODE()
isso é pra saber se o código tá sendo executado dentro de uma interrupção. Isso era pra ter vindo naquele PR daquelas funções extras do CMSIS q eu criei, mas só deu problema mesmo agr q eu tive q usar as funções, aí ele tentou compilar e não conseguiu.

2021-09-18 14:44 UTC, renanmoreira17 commented on Core/Src/modo.c
> +            set_rgb_led(selected_mode.cor, BLINK200);
não kkkkkk vou consertar aqui, vlw!

2021-09-18 14:46 UTC, renanmoreira17 commented on Core/Src/throttle_control.c
> +        }
é porque essas “funções" *_value são, na vdd, macros. Eles expandem pra mais de uma linha de código, aí n dá pra deixar nesse `if` sem chaves.

2021-09-19 20:05 UTC, FelTell approved these changes

2021-09-20 19:17 UTC, renanmoreira17 commented on Core/Src/throttle_control.c
> +        }
@luizaaraujo1 vou fechar essa Conversation. Mas se ainda tiver ficado alguma dúvida sobre isso, só me chamar

2021-09-20 19:27 UTC, merged