Leitura variáveis inversor
Tesla-UFMG/ECU pull request #39
Opened 2021-10-12 20:47 UTC by joaovictorchaves

2021-10-13 21:18 UTC, renanmoreira17 commented on Core/Inc/CAN/inverter_can.h
> +
Aqui não é o melhor lugar pra definir isso, já q esse arquivo é incluído em outros lugares q n tem nenhuma relação com leitura de dados da can (como no initializers.c). Acho melhor vc criar um arquivo só pra fazer essa lógica

2021-10-13 21:18 UTC, renanmoreira17 commented on Core/Inc/CAN/inverter_can.h
> +int16_t dataInverter[NUM_STATES];
move pro .c

2021-10-13 21:32 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
>  		}
pra melhorar a legibilidade, muda essa bloco para:
```cpp
for(int i = 0; i < 4; ++i) {
    can_vars_e var_name = get_var_name_from_id_and_pos(idInverter, i);
    if (var_name != -1) {
         uint16_t data = RxData[i*2] << 8 | RxData[i*2 + 1];
         store_value(var_name, data);
    }
}
```

2021-10-13 21:34 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +void store_value(can_vars_e var_name, int value)
value tem q ser `uint16_t`

2021-10-13 21:34 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +int get_value(can_vars_e var_name)
tipo de retorno tem q ser `uint16_t`

2021-12-11 22:55 UTC, renanmoreira17 requested changes
Conversa com o @FelTell depois, pq eu acho que suas mudanças podem dar conflito com as dele

2021-12-11 22:55 UTC, renanmoreira17 commented on Core/Inc/CAN/inverter_can_data_manager.h
> +uint32_t idInverter;
não parece ter necessidade dessa variável ser global, remove ela

2021-12-11 22:55 UTC, renanmoreira17 commented on Core/Inc/CAN/inverter_can_data_manager.h
> +int16_t dataInverter[NUM_STATES];
move pro .c, transforma em `uint32_t` e faz ela ser `static`

2021-12-11 22:55 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +		idInverter = RxHeader.Identifier;
pode instancia a variável aqui, n precisa criar ela no .h

2021-12-11 22:55 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +				uint16_t data = (RxData[i*2 + 1] << 8) | RxData[i*2];
cria uma função no util.c pra converter 2 bytes de `uint8_t` em 1 byte de `uint16_t`, aí passa esse código pra função e chama ela aqui pra melhorar a legibilidade

2021-12-15 17:29 UTC, joaovictorchaves commented on Core/Inc/CAN/inverter_can_data_manager.h
> +    ENTRY(alarm_m_r, 203, 2)
Teste

2021-12-15 18:34 UTC, FelTell requested changes

2021-12-15 18:34 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
> +				uint16_t data = uint8_to_uint16(RxData[i*2 + 1], RxData[i*2]);
O nome `uint8_to_uint16` não é o ideal. Algo como `two_uint8_to_one_uint16` fica mais claro

2021-12-15 23:15 UTC, FelTell approved these changes

2021-12-16 02:09 UTC, renanmoreira17 requested changes

2021-12-16 02:09 UTC, renanmoreira17 commented on Core/Src/util.c
> +}
```suggestion
uint16_t concatenate_two_uint8_to_uint16(uint8_t* data) {
    return (data[1] << 8 | data[0]);
}
```

2021-12-16 02:09 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +				uint16_t data = concatenate_two_uint8_to_uint16(RxData[i*2 + 1], RxData[i*2]);
```suggestion
				uint16_t data = concatenate_two_uint8_to_uint16(RxData + i*2);
```

2021-12-16 02:09 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can_data_manager.c
> +#include "CAN/inverter_can.h"
vc n deveria incluir isso aqui, vai dar dependência cíclica

2021-12-16 02:09 UTC, renanmoreira17 commented on Core/Inc/CAN/inverter_can.h
> +static uint32_t dataInverter[NUM_STATES];
essa variável tem q ir pro inverter_can_data_manager.c
outra coisa, ela tá em `camelCase`, o nosso padrão é `snake_case`

2021-12-17 19:07 UTC, joaovictorchaves commented on Core/Inc/CAN/inverter_can.h
> +static uint32_t dataInverter[NUM_STATES];
Concordo que devia estar lá, mas no último review tinha pedido para colocar no inverter_can

2021-12-17 20:40 UTC, renanmoreira17 approved these changes

2021-12-17 21:12 UTC, merged