Verificação erro de comunicação com inversor
Tesla-UFMG/ECU pull request #40
Opened 2021-10-12 21:06 UTC by joaovictorchaves

2021-12-08 01:35 UTC, FelTell requested changes
Como o Renan disse, faça merge com o PR #39 finalizado. Mas dei uma olhada pra entender a lógica e testei com a ECU, então esses feedbacks serão válidos.

2021-12-08 01:35 UTC, FelTell commented on Core/Src/main.c
> +};
Definir isso pelo cube. Por organização, mas mais importante, esse código será apagado quando um novo código for gerado, então usar o cube pra isso

2021-12-08 01:35 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
> +	osTimerStart(inverter_can_timerHandle, 2000 / portTICK_PERIOD_MS);
O osTimerStart vai ser chamado aqui por meio de uma interrupção (o callback de receber mensagem é uma interrupção). Com isso o timer não será iniciado.  Cria uma tarefa e chama essa tarefa por meio de uma queue, flag ou semaforo (eu faria por flag ou semaphoro)
@renanmoreira17 o que vc acha? Precisa chamar uma tarefa só pra iniciar o timer.

2021-12-08 01:35 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
> +		check_inverter_comm_error(NULL);
Coloca o `check_for_errors()` direto aqui. Deixa essa função `check_inverter_comm_error(NULL)` só para o callback do timer. Facilita debug

2021-12-08 01:35 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
> +	osTimerStart(inverter_can_timerHandle, 2000 / portTICK_PERIOD_MS);
Entendi o motivo dessa função aqui, mas esse initialize é chamado antes do kernel do RTOS iniciar, então não funciona. 
Pode colocar o `osTimerStart` antes do for da tarefa que ele vai tá. Se usar semaphoro nem vai precisar.

2021-12-08 01:35 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
> +	osTimerStart(inverter_can_timerHandle, 2000 / portTICK_PERIOD_MS);
Cuidado com esse tempo. O tempo da diferença entre o tempo atual e da ultima mensagem pode ser igual. Colocar tempos diferentes

2021-12-08 01:35 UTC, FelTell commented on Core/Src/main.c
> +};
Bom disso que vc vai poder criar o timer pelo cube e nem vai precisar apagar essas linhas rs

2021-12-11 23:02 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +	osTimerStart(inverter_can_timerHandle, 2000 / portTICK_PERIOD_MS);
mas pera, o proprio callback do timer inicia ele mesmo? é só fazer o timer ser `osTimerPeriodic` que isso já acontece naturalmente. Eu vi q vc usa essa função pra inicializar também, mas, nesse caso, é melhor usar outra função, não é legal usar função de callback pra outro propósito q n seja callback

2021-12-12 02:32 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
> +	osTimerStart(inverter_can_timerHandle, 2000 / portTICK_PERIOD_MS);
Faz sentido, ta bem confuso desse jeito. Mas ainda assim precisa criar uma tarefa pra isso, o `osTimerStart` é usado pra resetar o timer se tudo estiver certo, então precisa ser chamado de alguma forma no callback de recebimento.

2022-01-05 21:23 UTC, FelTell commented
Substituído pelo #60 que está com branch mais atualizada

2022-01-05 21:23 UTC, closed without merging