Tratando erro de CAN bus off
Tesla-UFMG/ECU pull request #45
Opened 2021-11-24 03:31 UTC by FelTell

Para tratar o erro de bus off da CAN do inversor temos duas opções, em ambas o erro é corrigido resetando o bit de INIT da can: 

- RTD inativo: não vai ser datalogado
- RTD ativo: sair de RTD e deixar flag de evento setada para ser datalogada

O objetivo é garantir a segurança do veículo e ficar evidente quando o veiculo está com erro de bus off em movimento

No caso da CAN geral apenas será setado uma flag de aviso e o erro corrigido resetando o bit de INIT da can.

(A sirene irar tocar temporariamente para verificarmos a frequencia do erro)

2021-12-08 00:34 UTC, renanmoreira17 requested changes

2021-12-08 00:34 UTC, renanmoreira17 commented on Core/Src/CAN/general_can.c
> +    if(ErrorStatusITs == FDCAN_IT_BUS_OFF){
```suggestion
    if(ErrorStatusITs |= FDCAN_IT_BUS_OFF){
```
porque se tiver qualquer outro erro junto com o `BUS_OFF` ele n vai cair aq

2021-12-08 00:34 UTC, renanmoreira17 commented on Core/Src/main_task.c
> +                    exit_RTD();
Acho q esse tratamento tá mt rígido, bus off pode acontecer esporadicamente por causa de acumulo de erro de transmissão ao longo do tempo. Acho q vc n deve desativar o RTD prontamente, o melhor tratamento seria vc verificar se aconteceu bus off num período de tempo curto, e desativar o RTD só nessa situação.

2021-12-08 00:34 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +    if(ErrorStatusITs == FDCAN_IT_BUS_OFF){
Mesma questão de cima

2021-12-08 00:34 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +            HAL_GPIO_WritePin(C_RTDS_GPIO_Port, C_RTDS_Pin, GPIO_PIN_RESET);
isso é de debug né? coloca num guard, n deixa solto assim n

2021-12-08 02:51 UTC, FelTell commented on Core/Src/main_task.c
> +                    exit_RTD();
Vou remover esse tratamento de erro. Com o #40 será possível desativar o RTD quando não receber mensagem por muito tempo

2021-12-10 17:36 UTC, renanmoreira17 requested changes

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +    if(ErrorStatusITs |= FDCAN_IT_BUS_OFF){
socorro, eu sugeri errado pra vc kkkkkkkkk
na vdd era:
```suggestion
    if(ErrorStatusITs | FDCAN_IT_BUS_OFF){
```
`|=` é ou-atribuição. Funciona, mas n é isso q vc quer rs

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +        if (HAL_FDCAN_DeactivateNotification(hfdcan, FDCAN_IT_BUS_OFF) != HAL_OK) {
Pq desativar notificação? Se vc fizer isso, vc nunca mais vai ser sinalizado de erro de bus off. Me explica melhor o q vc queria atingir com isso

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +        osThreadFlagsSet(t_main_taskHandle, BUS_OFF_ERROR_FLAG);
Tava pensando aq: cria uma função genérica e mais descritiva pra isso aq, tipo `issue_error`, q recebe a flag de erro. Aí, na função, vc faz esse set da thread flag. Dps muda nos lugares pra usar a função. Isso é só pra aumentar a legibilidade do código.

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +        set_debugleds(DEBUGLED1,FASTBLINK,10);
espaço dps das vírgulas

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/RTD.c
> +    if(/*is_brake_active && !is_throttle_active &&*/ !error_flags && (race_mode != ERRO))
opa, acho q isso veio sem querer rs

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/datalog_acquisition.c
>  		flag_ecu_1 = (get_individual_flag(ECU_control_event_id, 0xffffffff) >> 16);     // valor da flag é passado e shiftado para a direita 16x
formatação tá meio bugada aq

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/datalog_acquisition.c
> +uint32_t event_flag;
`static`
https://www.c-programming-simple-steps.com/static-keyword-in-c.html. Da uma olhada na seção “Using the C static keyword outside of a function"

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        //check_for_errors(is_there_APPS_error, APPS_ERROR_FLAG);           //verifica a plausabilidade dos APPSs
veio errado?

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/main_task.c
> +                    if (HAL_FDCAN_ActivateNotification(&hfdcan1, FDCAN_IT_BUS_OFF, 0) != HAL_OK) {
isso era o par daquele deactivateNotification, né? Psé, isso n vai funcionar mt bem, pq vc só consegue mudar os registradores de configuração da CAN se ela tiver em modo INIT. Ou seja: se o bit INIT do CCCR tiver em 1. Isso vai ser verdade quando der BusOff, mas vc limpa o bit lá no callback, então essa linha aq nunca vai surtir efeito.

2021-12-10 17:36 UTC, renanmoreira17 commented on Core/Src/main_task.c
> +                    osTimerStart(tim_inverter_BUS_OFF_errorHandle, 2000/portTICK_PERIOD_MS);
coloca o periodo de espera em um define

2021-12-10 23:19 UTC, FelTell commented
subsituido por #51

2021-12-10 23:19 UTC, closed without merging