Implementaçao logica botao
Tesla-UFMG/ECU pull request #46
Opened 2021-11-25 21:49 UTC by GiovanniPasa

Implementação da logica do botão e alteração na logica de "traction control" dos modos e definição dentro da struct de modos o controle dinamico a ser utilizado por cada modo e criação de uma variavel global que define se o controle será habilitado

2021-12-06 14:20 UTC, FelTell requested changes
Na próxima vez prestar atenção no nome da branch. Colocar o ECU3.0/... e o NomeAssim ou nome_assim.
Dá um merge com a develop e resolve os conflitos.

2021-12-06 14:20 UTC, FelTell commented on Core/Src/DynamicControls/enable_control.c
> +	            	set_global_var_value(DYNAMIC_CONTROL, true);
Aqui poderia usar a flag de evento, não precisaria nem dessa váriavel global. Você até criou a `DYN_CTRL_FLAG` e não usou ela pra nada.

2021-12-06 14:20 UTC, FelTell commented on Core/Src/DynamicControls/enable_control.c
> +void enable_dynamic_ctrl(){
Coloca uns comentários explicando o que a função faz. Ela é simples, mas bom explicar.

2021-12-06 14:20 UTC, FelTell commented on Core/Src/torque_manager.c
> +		     // rampa de torque
Esse código ta repetindo la embaixo. Cria uma função só pra ele. Cuidado, o código de controle lateral da luiza mudou um pouco a lógica, da uma merge com a branch develop antes.

2021-12-06 14:20 UTC, FelTell commented on Core/Src/DynamicControls/enable_control.c
> +	bool is_RTD_active = get_individual_flag(ECU_control_event_id, RTD_FLAG);
Porque esperar RTD?

2021-12-06 14:26 UTC, FelTell requested changes

2021-12-06 14:26 UTC, FelTell commented on Core/Src/DynamicControls/enable_control.c
> +	            	set_global_var_value(DYNAMIC_CONTROL, false);
Precisa de ter um feedback pro piloto indicando se o botão ativou ou n o controle dinâmico, isso vamos ter que conversar com a galera de aquisição, mas seria legal um feedback no led RGB também. Não precisa implementar isso agora, mas coloca um //todo pra lembrar disso.

2021-12-06 18:05 UTC, GiovanniPasa commented on Core/Src/DynamicControls/enable_control.c
> +}
não vi essa config vou tentar mudar

2021-12-08 00:37 UTC, renanmoreira17 requested changes
Dá merge com a develop antes pq algumas coisas aq vão ter q mudar, n faz sentido revisar nesse caso

2022-01-15 20:06 UTC, closed without merging