Reestruturação do código de cálculo do APPS
Tesla-UFMG/ECU pull request #48
Opened 2021-12-08 17:09 UTC by luizaaraujo1

2021-12-11 19:09 UTC, FelTell requested changes

2021-12-11 19:09 UTC, FelTell commented on Core/Inc/throttle.h
> +#define APPS1_MIN 1900
Comenta da onde que vem esses valores e linka a planilha

2021-12-11 19:09 UTC, FelTell commented on Core/Src/throttle.c
> +        }
coloque comentários

2021-12-11 19:09 UTC, FelTell commented on Core/Src/throttle.c
> +        if(APPS2 < value[i]) {
pode ter um caso desse if nunca ser true, msm com o for. Tratar esse caso

2021-12-11 19:09 UTC, FelTell commented on Core/Src/throttle.c
> +            }
comentários aqui tbm

2021-12-11 20:49 UTC, renanmoreira17 requested changes
Grazadeus mudou essa função, naiceee

2021-12-11 20:49 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +    float fix_add[APPS_MATRIX_LENGTH] = {APPS2_FIX_ADD};
faz todas essa variáveis `static`, já q elas nunca vão mudar

2021-12-11 20:49 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +    return percentage;
```suggestion
    return min(1000, percentage);
```

2021-12-11 20:49 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +    float fix_add[APPS_MATRIX_LENGTH] = {APPS1_FIX_ADD};
`static`

2021-12-16 01:21 UTC, FelTell requested changes

2021-12-16 01:21 UTC, FelTell commented on Core/Src/throttle.c
> +uint16_t throttle_calc(uint16_t APPS, uint16_t *value, float *fix_mul, float *fix_add, uint16_t MAX) {
Eu gostei muito de ter uma função única para os dois cálculos, mas a lógica que usamos agr não é muito compatível com ela, e acho que da pra deixar essa lógica muito melhor. 

No código atual, nós usamos o valor de APPS2 para calcular a porcentagem do acionamento do pedal e usamos esse valor para calcular a o valor esperado de APPS1. Sempre achei isso confuso, e com essa função fica ainda mais. A função é pra calcular o acionamento do pedal, mas ela tbm calcula o valor esperado do ADC do apps1.

Então, pq não calcular a porcentagem do acionamento do dois pedais? Teremos um `apps1_throttle_percent` e `apps2_throttle_percent`. Compara se esses dois valores tão entre 10% e depois envia `apps_throttle_percent` que é a média do dois pedais.

Vai ter que mudar como isso é calculado na planilha também, mas pra mim isso só simplifica a planilha e o código. Fazer a média dos dois sinais pode deixar o resultado melhor também

2021-12-16 01:21 UTC, FelTell commented on Core/Src/throttle.c
> +uint16_t throttle_calc(uint16_t APPS, uint16_t *value, float *fix_mul, float *fix_add, uint16_t MAX) {
Tá confuso o que é `uint16_t APPS`, coloca `uint16_t  APPS_VALUE`.
`uint16_t *value` tbm tá, acho que `uint16_t *ref_value` ou algo assim é melhor
Diria o msm para `uint16_t MAX`, mas esse acho que vai remover com a sugestão anterior

2021-12-16 01:21 UTC, FelTell commented on Core/Src/throttle.c
> +        static float apps2_fix_add[APPS_MATRIX_LENGTH] = {APPS2_FIX_ADD};
Da um tab antes do "=" pra ficar alinhado

2021-12-16 01:21 UTC, FelTell commented on Core/Src/throttle.c
> +        static float apps2_fix_add[APPS_MATRIX_LENGTH] = {APPS2_FIX_ADD};
Na vdd eu não gostei desse trem aqui não. Acho que da pra simplificar mantendo os defines do jeito que tá. Tenta usar matriz ou olha como Renan usou define com vetores no CAN/CAN_IDs.h

2021-12-16 01:21 UTC, FelTell commented on Core/Src/throttle.c
> +         || APPS1 > APPS1_MAX           //Se o valor de APPS1 for acima do seu máximo
Matem o padrão aqui ou tudo `APPSX_MXX_VALUE` ou `APPSX_MXX`. Msm coisa com o `>` e `>= `
Coloca `APPS2_MIN_VALUE` também, mesmo que ele seja 0, pra manter o padrão

2021-12-16 01:49 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +uint16_t throttle_calc(uint16_t APPS, uint16_t *value, float *fix_mul, float *fix_add, uint16_t MAX) {
RTzão

2021-12-16 02:01 UTC, renanmoreira17 requested changes
Faz as mudanças que o Telles propôs, aí eu reviso de novo

2021-12-16 02:05 UTC, FelTell commented on Core/Src/throttle.c
> +        static float apps2_fix_add[APPS_MATRIX_LENGTH] = {APPS2_FIX_ADD};
Justo, acho que colocar em struct ja ajuda

2021-12-16 02:41 UTC, FelTell commented on Core/Inc/throttle.h
> +// https://onedrive.live.com/view.aspx?resid=52B70A6379F6F8AB!115743&ithint=file%2cxlsx&authkey=!AJ8JGeSHTz3KdoQ
por mais que por mim só usava o onedrive, coloca essa planilha no drive de controle e linka ela pelo drive

2022-01-06 18:58 UTC, FelTell requested changes

2022-01-06 18:58 UTC, FelTell commented on Core/Src/throttle.c
> +        apps2_value = 1200;//ADC_DMA_buffer[APPS2_E];
ops

2022-01-06 18:58 UTC, FelTell commented on Core/Src/throttle.c
> +        check_for_errors_with_timeout(is_there_SU_F_error, SU_F_ERROR_FLAG, tim_SU_F_errorHandle, SU_F_ERROR_TIMER);     //verifica se a placa de freio está em curto
tira o acento do comentário em "está" (e qualquer outro acento tbm) o bot não gosta e as vezes buga por isso

2022-01-06 18:58 UTC, FelTell commented on Core/Src/throttle.c
> +        throttle_percent = (apps1_throttle_percent + apps2_throttle_percent)/2;     //a porcentagem final do pedal é a media dos dois apps
igual tem o `abs` pra absoluto faz um `avg` pra média. e ja aproveita e usa no calculo do `cg_speed` em lateral _control.c

2022-01-06 18:58 UTC, FelTell commented on Core/Src/throttle.c
> +        apps_ref apps2_ref = {APPS2_REF, APPS2_FIX_MUL, APPS2_FIX_ADD};     //para o calculo da porcentagem.
define apenas subsistitui a termo pelo valor então vc tá fazendo isso aqui ó:
`apps_ref apps1_ref = {2065, 2260, 2465, 2640, 2835, 3020, 3205, 3400, 3575, 0, 1.5385, 0.4878, 0.5714, 0.5128, 0.5405, 0.5405, 0.5128, 0.5714, 0, -3177, -802.4, -1008, -853.8, -932.4, -932.4, -843.6, -1043};`

No fim acho que funciona, mas ta feio. Mexe no .h onde tá o define, vou fazer um comentário la

2022-01-06 18:58 UTC, FelTell commented on Core/Inc/throttle.h
> +#define APPS1_FIX_ADD 0, -3177, -802.4, -1008, -853.8, -932.4, -932.4, -843.6, -1043
```suggestion
#define APPS1_REF       {2065, 2260, 2465, 2640, 2835, 3020, 3205, 3400, 3575}
#define APPS1_FIX_MUL   {0, 1.5385, 0.4878, 0.5714, 0.5128, 0.5405, 0.5405, 0.5128, 0.5714}
#define APPS1_FIX_ADD   {0, -3177, -802.4, -1008, -853.8, -932.4, -932.4, -843.6, -1043}
```

2022-01-06 18:58 UTC, FelTell commented on Core/Inc/throttle.h
> +#define APPS2_FIX_ADD 0, -442.1, 179.5, 161.1, 151.4, 167.5, 142.9, 148.6, 126.5
mesma coisa

2022-01-07 21:47 UTC, renanmoreira17 requested changes

2022-01-07 21:47 UTC, renanmoreira17 commented on Core/Inc/throttle.h
> +} apps_ref;
põe essa struct no .c

2022-01-07 21:47 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +uint16_t throttle_calc(uint16_t apps_value, apps_ref ref) {
passa esse `apps_ref` por referência
```suggestion
uint16_t throttle_calc(uint16_t apps_value, const apps_ref* ref) {
```
se não vc vai copiar aquela struct grandona toda vez q chama essa função, mas não precisa. Isso vai ser bem ruim de performance

2022-01-07 21:47 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        apps_ref apps1_ref = {APPS1_REF, APPS1_FIX_MUL, APPS1_FIX_ADD};     //valores de referencia e parametros
`const static`

2022-01-07 21:47 UTC, renanmoreira17 commented on Core/Src/throttle.c
> +        apps_ref apps2_ref = {APPS2_REF, APPS2_FIX_MUL, APPS2_FIX_ADD};     //para o calculo da porcentagem.
`const static`

se vc n fizer essas variaveis estaticas, o stack do RTOS pra essa tarefa n vai aguentar não kkkkk

2022-01-10 17:12 UTC, luizaaraujo1 commented on Core/Inc/throttle.h
> +} apps_ref;
Por que?

2022-01-10 17:18 UTC, renanmoreira17 commented on Core/Inc/throttle.h
> +} apps_ref;
Pelo o que parece, vc só usa essa struct no .c, então n precisa declarar ela no .h (quanto menos coisa no .h, melhor).
A n ser que eu já esteja enganado e vc use em algum outro lugar que n seja o .c, nesse caso pode deixar

2022-01-10 17:21 UTC, luizaaraujo1 commented on Core/Inc/throttle.h
> +} apps_ref;
Entendi, show

2022-01-11 01:33 UTC, FelTell approved these changes

2022-01-11 01:41 UTC, renanmoreira17 approved these changes

2022-01-11 11:20 UTC, merged