Tratamento de erros com timers
Tesla-UFMG/ECU pull request #49
Opened 2021-12-08 18:25 UTC by FelTell

Código para permitir que o tratamento de erro não seja imediato, e sim aguarde um determinado tempo para ser tratado.

2021-12-11 21:44 UTC, renanmoreira17 requested changes

2021-12-11 21:44 UTC, renanmoreira17 commented on Core/Inc/error_treatment.h
> +#include "global_instances.h"
precisa ser aqui? tenta mover pro .c

2021-12-11 21:44 UTC, renanmoreira17 commented on Core/Inc/error_treatment.h
> +void errors_with_timer_callback(void *argument);
não precisa

2021-12-11 21:44 UTC, renanmoreira17 commented on Core/Inc/throttle.h
> +#define APPS_ERROR_TIMER 100 - THROTTLE_DELAY   //Regulamento: T.4.2.5 (2022)
parênteses

2021-12-11 21:44 UTC, renanmoreira17 commented on Core/Src/main.c
> +#include "error_treatment.h"
nao precisa
é so vc declarar o prototipo da função de callback do timer aq, melhor do q incluir o header inteiro

2021-12-11 21:44 UTC, renanmoreira17 commented on Core/Src/main.c
> +extern void errors_with_timer_callback(void *argument);
igual vc fez aq, na real kkkk
pode só remover o include lá em cima

2021-12-11 21:44 UTC, renanmoreira17 commented on Core/Src/error_treatment.c
> +void check_for_errors_with_timer(bool (* areThereErrors)(), uint32_t flagError, osTimerId_t timerHandler, uint16_t timerAmount) {
muda o nome da função pra:
`check_for_errors_with_timeout`
deixa o propósito mais claro

2021-12-12 02:22 UTC, FelTell commented on Core/Inc/error_treatment.h
> +void errors_with_timer_callback(void *argument);
Por que não? vai virar uma declaração implícita. ou então entendi errado

2021-12-12 02:28 UTC, FelTell commented
Vou da merge com a develop primeiro na #51 para depois da merge nessa, resolver conflitos e aplicar aquelas mudanças na error_treatment

2021-12-12 14:51 UTC, renanmoreira17 commented on Core/Inc/error_treatment.h
> +void errors_with_timer_callback(void *argument);
então, mais ou menos....
colocar função no header, de certa forma, tbm é uma declaração implícita da função. Vc só tá dizendo pra todo mundo que incluir esse header que existe uma função em algum lugar com aquela assinatura. Na realidade, vc nem precisaria implementar a função no .c correspondente daquele .h, vc é totalmente livre de implementar a função em outro lugar. Isso de definir uma função global no .h e implementar ela no .c de mesmo nome é só uma convenção mesmo.
Nesse caso aqui, o que vc precisaria fazer é declarar um protótipo dessa função na main.c com a exata mesma assinatura que vc implementa aqui. O compilador vai procurar uma implementação desse protótipo na hora de linkar, e vai dar erro se n achar (então é uma coisa safe de fazer). Isso é bem melhor do q ter q registrar o callback no .h (🤢) e incluir o hedaer inteiro na main.c só por causa desse callback.

2021-12-12 17:55 UTC, FelTell commented on Core/Inc/error_treatment.h
> +void errors_with_timer_callback(void *argument);
aa tendi, é só o callback, justissimo

2021-12-13 01:25 UTC, renanmoreira17 approved these changes
Da merge com o PR que vc deu merge agr há pouco, conserta essas issues aq e pode dar merge

2021-12-13 01:25 UTC, renanmoreira17 commented on Core/Src/error_treatment.c
> +    osEventFlagsSet(ECU_control_event_id, flagError);   // seta flag de estado com a flag flagError
`issue_error`

2021-12-13 01:25 UTC, renanmoreira17 commented on Core/Src/error_treatment.c
> +        osEventFlagsClear(ECU_control_event_id, flagError);     // limpa flag de estado flagError
`clear_error`

2021-12-13 01:53 UTC, merged