Tratando erro de CAN bus off (refeito)
Tesla-UFMG/ECU pull request #51
Opened 2021-12-10 23:18 UTC by FelTell

o PR #45 estava dando problema, para facilitar decidir refaze-lo

2021-12-11 22:49 UTC, renanmoreira17 requested changes

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Inc/CAN/inverter_can.h
> +void inverter_BUS_OFF_error_callback(void *argument);
não precisa

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Inc/error_treatment.h
> +#include "global_instances.h"
não

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Inc/global_definitions.h
> +#define GENERAL_BUS_OFF_ERROR_FLAG  1 << 8
parênteses

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Inc/global_definitions.h
> +#define INVERTER_BUS_OFF_ERROR_FLAG 1 << 22
parêntese

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Src/CAN/CAN_handler.c
> +    //  TxHeader.Identifier = 0x321;
pode tirar esse comentário

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +    osEventFlagsClear(ECU_control_event_id, INVERTER_BUS_OFF_ERROR_FLAG); // limpa flag de estado do erro
cria uma outra função pra essa rs
`clear_error`

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Src/main_task.c
> +                exit_RTD();                                                                     //sai de RTD caso o erro esteja presente
indentação

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Src/error_treatment.c
> +void issue_error(uint32_t flagError){
adiciona um parâmetro aqui:
`void issue_error(uint32_t flagError, bool should_set_control_event_flag = true)`
(n tenho certeza se o valor default do parâmetro vem aqui ou na declaração)
aí, se vier true, vc tbm seta a flag de controle, aí vc deixa só uma chamada dessa função nos lugares q precisam setar erro

2021-12-11 22:49 UTC, renanmoreira17 commented on Core/Src/main_task.c
> +            case INVERTER_BUS_OFF_ERROR_FLAG:
documenta o tratamento desse das, como é mais diferenciado dos outros. Faz um textinho em cima explicando, ao invés de só comentar linha por linha (n precisa tirar os comentários por linha, só adicionar o texto em cima)

2021-12-12 01:40 UTC, FelTell commented on Core/Inc/error_treatment.h
> +#include "global_instances.h"
preciso colocar um include ali pq se n ele n reconhece o tipo uint32_t. coloquei o cmsis_os.j no lugar

2021-12-12 14:29 UTC, renanmoreira17 requested changes

2021-12-12 14:29 UTC, renanmoreira17 commented on Core/Inc/error_treatment.h
> +#include "cmsis_os.h"
inclui o `<stdint.h>`, é mais leve que incluir o cmsis inteiro

2021-12-12 14:29 UTC, renanmoreira17 commented on Core/Src/error_treatment.c
> +        issue_error(flagError, true);   // seta flag de estado com a flag flagError
```suggestion
        issue_error(flagError, /*should_set_control_event_flag=*/true);   // seta flag de estado com a flag flagError
```
sempre faz isso quando vc chamar uma função com um literal, assim a gente sabe o que aquele `true` significa

2021-12-12 14:29 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can.c
> +        issue_error(INVERTER_BUS_OFF_ERROR_FLAG, false);    // chama o erro para a main_task tratar
mesma questão do comentário

2021-12-12 14:29 UTC, renanmoreira17 commented on Core/Inc/main_task.h
> +#define BUS_OFF_ERROR_TIME (2000/portTICK_PERIOD_MS)
Não é pra agora, mas dps seria interessante criar um .h só pra esse tipo de define, aí a gnt sabe exatamente onde ir se quiser mudar alguma configuração. Tipo um `car_parameters.h` e move todos esse defines pra lá, aí fica tudo centralizado e fácil de mudar. Mas n é pra agora, mas dps seria interessante fazer isso sim

2021-12-12 14:29 UTC, renanmoreira17 commented on Core/Src/CAN/general_can.c
>  static FDCAN_HandleTypeDef* can_ptr;;
tem um `;` a mais, remove ele

2021-12-12 18:02 UTC, FelTell commented on Core/Inc/main_task.h
> +#define BUS_OFF_ERROR_TIME (2000/portTICK_PERIOD_MS)
tem a contants.h, acha que usa ela? Tem até que da uma limpa nela até, ficaria pra depois.

2021-12-12 22:41 UTC, renanmoreira17 commented on Core/Inc/main_task.h
> +#define BUS_OFF_ERROR_TIME (2000/portTICK_PERIOD_MS)
pode ser, mas põe no backlog isso pra fazer dps

2021-12-12 22:42 UTC, renanmoreira17 approved these changes

2021-12-13 01:02 UTC, merged