Terceiro fix da função de calculo de velocidade
Tesla-UFMG/ECU pull request #52
Opened 2021-12-15 23:10 UTC by FelTell

uma hora vai

2021-12-16 14:09 UTC, FelTell commented
Testei na ECU, com a função nova o valor de clock está correto. Com a antiga vem um valor errado. Também mudei a configuração de clock sem o prescaler pra timer pra validar a função e obtive o comportamento esperado.

2021-12-17 20:05 UTC, renanmoreira17 requested changes

2021-12-17 20:05 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +    min_timeout = (10*3.6*2*M_PI * WHEEL_RADIUS / SPEED_SENSOR_TEETH_QUAN) * 1000 / MIN_SPEED;
aproveitando q vc tá mexendo nisso, tem como criar uma função separada pra calcular esse valor? To vendo muita coisa repetida, e essa expressão é meio complexa de entender. Criando uma função vai melhorar a legibilidade.
Pode criar aq mesmo nesse .c

2021-12-22 01:08 UTC, renanmoreira17 requested changes
dá merge com a develop antes de pushar tbm, tem mais atualização lá rs

2021-12-22 01:08 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +uint32_t calculate_timeout(uint32_t speed);
faz essas funções `static inline`

2021-12-22 01:29 UTC, renanmoreira17 approved these changes

2021-12-22 01:29 UTC, renanmoreira17 commented on Core/Src/speed_calc.c
> +uint32_t get_tim2_freq() {
aqui e nas outras funções tbm precisa ser `static inline`

2021-12-22 16:32 UTC, merged