Consertando issues de clang-tidy
Tesla-UFMG/ECU pull request #59
Opened 2021-12-28 02:13 UTC by renanmoreira17

Essas mudanças foram geradas automaticamente, então pode ter vindo coisa inesperada.
@FelTell dá só uma passada de olho depois pra ver se mudou algo q não devia. Eu olhei e aparentemente tá OK, mas só pra garantir mesmo.

2021-12-28 14:06 UTC, FelTell requested changes

2021-12-28 14:06 UTC, FelTell commented on Core/Src/datalogger.c
> +	(void) argument;
Sei que o bot pede isso, mas achei feio kkkkk. Tem jeito melhor não? Fica muito jogado

2021-12-28 14:06 UTC, FelTell commented on Core/Src/throttle.c
>          return ((uint16_t) (1.75 * apps2_percentage + 1825));
ta fora do padrão que a gente usa 
if {
...
}

2021-12-28 14:06 UTC, FelTell commented on Core/Src/throttle.c
>          return ((uint16_t) (1.75 * apps2_percentage + 1825));
mas vai mudar com #48

2021-12-28 15:57 UTC, renanmoreira17 commented on Core/Src/DynamicControls/PID.c
> +		memset(pid->input_state, 0, 2U * sizeof(double)); // NOLINT
é pra avisar pro clang-tidy pra ignorar essa linha e n fazer sugestão pra ela. É pq ele tava querendo usar aquela `memset_s`, só q n tem essa função pra lib do stm

2021-12-28 15:58 UTC, renanmoreira17 commented on Core/Src/RTD.c
> +    }         return false;
acho q a identação bugou. Depois eu vou passar um clang-format nesses arquivos rs

2021-12-28 16:27 UTC, renanmoreira17 commented on Core/Src/datalogger.c
> +	(void) argument;
então, essa é a maneira "oficial" de ignorar parâmetro não utilizado, tipo como tem lá no código do cmsis:
<img width="889" alt="Captura de Tela 2021-12-28 às 13 24 03" src="https://user-images.githubusercontent.com/28550508/147586423-39993209-b0eb-43fb-8d67-5bc2177b391c.png">
(fica em Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c:1755)

Mass, a HAL tbm faz isso, mas ela tem uma macro:
<img width="757" alt="Captura de Tela 2021-12-28 às 13 26 04" src="https://user-images.githubusercontent.com/28550508/147586513-e005380c-e26f-46b3-870a-264308f66ad3.png">
que é essa `UNUSED`. Definição dela:
```cpp
#define UNUSED(x) ((void)(x))
```
Se vc achar melhor, eu posso criar uma versão dessa UNUSED pra a gnt. O q vc acha?

2021-12-28 16:28 UTC, renanmoreira17 commented on Core/Src/throttle.c
>          return ((uint16_t) (1.75 * apps2_percentage + 1825));
eu vou passar clang-format nesse código, vai tirar esses problemas de formatação todos rs

2021-12-28 16:31 UTC, FelTell commented on Core/Src/datalogger.c
> +	(void) argument;
gostei da unused, deixa mais claro o que tá fazendo

2021-12-28 16:49 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can_data_manager.c
> +can_vars_e get_var_name_from_id_and_pos(uint32_t id, int pos)
isso vai triggar a warning de novo, pq `int` = `int16_t`. Acho q n vale a pena mudar pra `int16_t`, pq se n vou ter q mudar em outros lugares e dá na mesma

2021-12-31 02:00 UTC, FelTell commented
Mudou alguma coisa sem ser formatação? 68 arquivos pra verificar é foda kkkkk. Mas tá muito bom, bem legal o clang-format. Só não sei como fazer ele sem da conflito em tudo msm

2022-01-03 21:30 UTC, renanmoreira17 commented
> Mudou alguma coisa sem ser formatação? 68 arquivos pra verificar é foda kkkkk. Mas tá muito bom, bem legal o clang-format. Só não sei como fazer ele sem da conflito em tudo msm

mudou algumas coisas do makfile e outras em relação ao `UNUSED`. De resto foi formatação mesmo. Se vc quiser, dá pra filtrar as mudanças por commit também lá em "Files changed”, mas se vc quiser confiar em mim, foi só isso q mudou mesmo kkk

2022-01-21 02:13 UTC, closed without merging