Verificação erro de comunicação com inversor e espera para RTD
Tesla-UFMG/ECU pull request #60
Opened 2022-01-05 21:22 UTC by FelTell

Com esse código o veículo sairá de RTD após ficar 500ms sem receber mensagem do inversor. Com isso finalmente o carro sairá de RTD quando o shutdown for acionado. 
Além disso o RTD só poderá ser acionado após 5s da primeira mensagem do inversor chegar. Uma forma de garantir que o segundo contator está fechado, já que o BMS não consegue ler o status do contator. Esse valor de 5s deve ser verificado se é adequado no veículo.

Coloquei os comentários em ingles para tentar padronizar no futuro. (pode ter erros rs)

2022-01-07 22:08 UTC, renanmoreira17 requested changes

2022-01-07 22:08 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can_error_manager.c
> +void inverter_comm_error(void *argument) {
só pra eu saber se entendi:
o objetivo é que assim que ligar o GLV fique em estado de erro constantemente, e quando ligar o TS ele sai. Tipo, não tem problema ficar em estado de erro antes de ligar o TS, é isso? Confere só se esse erro não vai interferir em nenhuma outra parte do código que é sensível a erro.

2022-01-07 22:08 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can_error_manager.c
> +                }
olha, eu acho q n precisa de timer pra essa lógica. Tipo, sempre que vc lê uma flag de thread, vc limpa ela (a n ser que vc passe a flag de n limpar quando ler). O que vc pode fazer é:

- Pede pra toda vez q receber mensagem, setar a flag q recebeu mensagem, igual já faz
- Vc lê essa flag aqui checando pelo timeout, igual já tá fazendo
- Se der timeout, é pq n recebeu mensagem nos ultimos tantos segundos. Ou seja: erro
- Se n der, é pq tá tudo bem.

O timer só adiciona uma layer desnecessária a mais rs

2022-01-07 22:49 UTC, FelTell commented on Core/Src/CAN/inverter_can_error_manager.c
> +void inverter_comm_error(void *argument) {
Exatamente.
Quem é sensivel ao erro é a main_task e a verificação para RTD. main_task só funciona depois de estar em RTD msm. E RTD não é pra ser aprovado quando tiver erro msm

2022-01-07 22:49 UTC, FelTell commented on Core/Src/CAN/inverter_can_error_manager.c
> +                clear_error(INVERTER_COMM_ERROR_FLAG);      // clear the error flag
justo rs

2022-01-07 22:51 UTC, FelTell commented on Core/Src/CAN/inverter_can_error_manager.c
> +                }
Não entendi. Essa lógica não é pra acionar erro, e sim para liberar o RTD depois do tempo de precharge (depois do segundo contator fechar). Por isso tem essa flag separada.

2022-01-19 20:24 UTC, renanmoreira17 approved these changes

2022-01-19 20:24 UTC, renanmoreira17 commented on Core/Src/CAN/inverter_can_monitor.c
> +#include <CAN/inverter_can_monitor.h>
“” no lugar de <>

2022-01-19 22:11 UTC, merged