Logica de reset pelo piloto
Tesla-UFMG/ECU pull request #68
Opened 2022-03-15 19:57 UTC by GiovanniPasa

Logica implementada por meio dos botões  de modo e RTD assim como a exigencia de não existencia de aceleração e que o pedal do freio esteja acionado

2022-03-16 00:30 UTC, FelTell reviewed
@renanmoreira17 o clang-tidy morreu help

2022-03-16 00:30 UTC, FelTell commented on Core/Inc/driver_settings/pilot_reset.h
> +#define RESET_BUTTONS_TIMEOUT 1000
Acho que 2s (contando os dois botões) é muito pra combinação. Mas sla, tinha que ver no carro

2022-03-16 00:30 UTC, FelTell commented on Core/Src/driver_settings/pilot_reset.c
> +        returns[1] =  osThreadFlagsWait(MODE_BTN_PRESSED_FLAG, osFlagsWaitAny, RESET_BUTTONS_TIMEOUT);
Complementando, essa lógica não tá mt legal. Quando apertar o botão de modo ele espera apertar o de RTD meio que infinitamente, tem o timeout, mas esse timeout só vai ser tratado depois de apertar o botão de modo dnv no `if`.  
Te dou duas sugestões:
- Usar timers pra manter a msm logica de acionamento;
- Usar outra lógica que envolve apertar tudo ao msm tempo (modo, RTD, CD e freio) usar uma `osThreadFlagsWait` pra esperar botão (esse na vdd vai ter que ser acionado por ultimo) e depois um `if `que verifica se tudo ta apertado (usa a função da HAL de ler pinos), se sim ele reseta a ECU.

2022-03-16 00:30 UTC, FelTell commented on Core/Src/driver_settings/pilot_reset.c
> +        returns[1] =  osThreadFlagsWait(MODE_BTN_PRESSED_FLAG, osFlagsWaitAny, RESET_BUTTONS_TIMEOUT);
Se usar a segunda opção o certo seria criar uma função pra encapsular a função da HAL (`HAL_GPIO_ReadPin` eu acho). Mas n preocupa com isso agora pq quero que seja refatorado essa lógica de botão 😬.

2022-03-16 00:58 UTC, GiovanniPasa commented on Core/Src/driver_settings/pilot_reset.c
> +        returns[1] =  osThreadFlagsWait(MODE_BTN_PRESSED_FLAG, osFlagsWaitAny, RESET_BUTTONS_TIMEOUT);
> Complementando, essa lógica não tá mt legal. Quando apertar o botão de modo ele espera apertar o de RTD meio que infinitamente, tem o timeout, mas esse timeout só vai ser tratado depois de apertar o botão de modo dnv no `if`. Te dou duas sugestões:
> 
> * Usar timers pra manter a msm logica de acionamento;
> * Usar outra lógica que envolve apertar tudo ao msm tempo (modo, RTD, CD e freio) usar uma `osThreadFlagsWait` pra esperar botão (esse na vdd vai ter que ser acionado por ultimo) e depois um `if `que verifica se tudo ta apertado (usa a função da HAL de ler pinos), se sim ele reseta a ECU.

na verdade o timeout faz ele passar a linha ent ele nao espera o botao de modo de novo, caso esse delay passe ele entra no if como timeout e retorna pro waitforever

2022-03-16 01:33 UTC, FelTell commented on Core/Src/driver_settings/pilot_reset.c
> +        returns[1] =  osThreadFlagsWait(MODE_BTN_PRESSED_FLAG, osFlagsWaitAny, RESET_BUTTONS_TIMEOUT);
Tava esquecendo que passava de linha rs. Tá certinho a lógica

2022-03-16 01:44 UTC, FelTell requested changes

2022-03-16 01:44 UTC, FelTell commented on Core/Src/driver_settings/pilot_reset.c
> +    uint32_t returns[2];
Muda o nome dessa variável pra algo mais claro, tipo: `thread_flag_status `e faz um enum com `mode_button` e `RTD_button`

2022-03-21 17:30 UTC, FelTell requested changes
Resolva as conversas que vc ja mexeu.

2022-03-21 17:30 UTC, FelTell commented on Core/Src/driver_settings/pilot_reset.c
> +        // TODO(Giovanni): refazer logica quando o button handler for implementado
vai precisar refazer nada não, a não ser que vc queira implementar algum long press. Coloque o osThreadFlagsSet na external_interrupt_handler que vai facilitar quando eu der merge no meu PR.

2022-03-21 17:55 UTC, GiovanniPasa commented on Core/Src/driver_settings/pilot_reset.c
> +        returns[1] =  osThreadFlagsWait(MODE_BTN_PRESSED_FLAG, osFlagsWaitAny, RESET_BUTTONS_TIMEOUT);
sobre a  osThreadFlagsSet acho que devo mudar a logica completamente e usar event flags, ja que segundo a wiki do cmsis threadflags tem o objetivo de serem usadas em somente uma thread, logo n sei se funcionará do jeito que está agora, qual sua opinião @FelTell ? Link da wiki:  https://www.keil.com/pack/doc/cmsis/RTOS2/html/group__CMSIS__RTOS__ThreadFlagsMgmt.html

2022-03-21 18:23 UTC, FelTell commented on Core/Src/driver_settings/pilot_reset.c
> +        returns[1] =  osThreadFlagsWait(MODE_BTN_PRESSED_FLAG, osFlagsWaitAny, RESET_BUTTONS_TIMEOUT);
na vdd, as duas vão da errado rs. 
Sobre a sua pergunta, não tem problema, seria só usar outra chamada para osThreadFlagsSet.
Problema que pensei aqui é o sobre como vai da clear nesse flag (que é importante depois de realizar a ação do botão). Se usar event flag tem que tomar cuidado, pode ser que uma tarefa de clear antes da outra. ThreadFlag é de boa nisso pq vc garante que as duas vão receber, agr quando apertar RTD a flag é setada e só vai ser limpa quando chegar na sua osThreadFlagsWait.

2022-03-22 14:02 UTC, FelTell submitted a review, later dismissed

2022-03-22 14:46 UTC, renanmoreira17 submitted a review, later dismissed

2022-03-22 14:46 UTC, renanmoreira17 commented on Core/Inc/util/util.h
> +#include "util/CMSIS_extra/global_variables_handler.h"
hm, acho melhor n introduzir essa dependência. Vou comentar melhor embaixo

2022-03-22 14:46 UTC, renanmoreira17 commented on Core/Inc/util/util.h
> +bool is_the_car_stationary(WHEEL_SPEEDS_t wheel_speeds);
Mas fica a seu critério qual vc escolhe. Minha orientação é:
Vc pretende usar essa função pra outros valores q n sejam diretamente a velocidade das rodas extraídas da variável global? Se ss, a segunda opção é melhor. Caso seja sempre da variável global, a primeira é melhor

2022-03-22 14:46 UTC, renanmoreira17 commented on Core/Src/driver_settings/pilot_reset.c
> +        //After that the system will be reseted
coloca um espaço dps do “//“, o clang-format pede isso (e pode colocar em outros lugares tbm se tiver acontecido)

2022-03-22 14:46 UTC, renanmoreira17 commented on Core/Src/driver_settings/pilot_reset.c
> +        if(is_brake_active && !is_throttle_active && is_the_car_stationary(wheel_speeds)){
e uma coisa complementando o comentário la de trás: vc ta passando as velocidades por copia e n precisa, ate pq é uma copia meio pesada (4 doubles = 256 bits, 8 ciclos de clock no mínimo). Porem, se vc implementar qualquer uma das sugestões q eu dei, n vai ser problema no final

2022-03-22 14:49 UTC, renanmoreira17 commented
@GiovanniPasa @FelTell uma coisa que me veio em mente aqui: será que n é melhor colocar um delay entre os passos da sequência n? Tipo, o piloto aperta um botão, aí espera 100ms pra verificar se o próximo botão foi apertado, e assim em diante. To pensando no caso mais raro de alguém apertar os todos os botões sem querer ou se uma interferência/mal contato fizer com q todos os botões flutuem por um tempo e resetar a ECU por acidente. Com o delay vc reduz essa chance

2022-05-18 19:30 UTC, luizaaraujo1 requested changes
Dar merge com a branch ECU3.0/adc_debug antes de enviar para develop

2022-05-18 19:30 UTC, luizaaraujo1 commented on Core/Inc/driver_settings/pilot_reset.h
> +#define RESET_BUTTONS_TIMEOUT 500
Testamos aqui e 500 não da tempo kkkk. Coloca 1000 que fica bom

2022-05-18 19:30 UTC, luizaaraujo1 commented on Core/Src/driver_settings/pilot_reset.c
> +        if (is_brake_active && !is_throttle_active && is_the_car_stationary()) {
TODO: Testar condições no carro montado

2022-05-19 10:42 UTC, FelTell commented
> Dar merge com a branch ECU3.0/adc_debug antes de enviar para develop

vou da n, aquele é outro PR que tem que aprovar

2022-05-19 11:43 UTC, luizaaraujo1 approved these changes

2022-05-19 11:47 UTC, merged