Better speed variables
Tesla-UFMG/ECU pull request #73
Opened 2022-05-03 12:47 UTC by FelTell

The old speed global variables didn't support the motor speeds and was unnecessary a float.

2022-05-24 22:45 UTC, renanmoreira17 requested changes
Agora que tá tudo virando X-macro, dps seria top mudar aquela lógica das variáveis globais pra X-macro tbm. Though eu acho que isso seria uma tarefa um pouquinho mais complexa, pq esse rolê das variáveis globais já tá cheia de macro comum pra todo lado. Mas seria interessante, porque aí pra registrar uma variável global nova seria só mudar em um lugar. @luizaaraujo1 olha com seus filhos depois de fazer isso, eu posso ajudar orientando

2022-05-24 22:45 UTC, renanmoreira17 commented on Core/Src/datalogging/speed.c
> +        WHEEL_ENCODER_SPEEDS_t encoder_speed = get_global_var_value(WHEEL_ENCODER_SPEEDS);
Pelo o que eu entendi, essa variável tem uma utilização 1:1. Você define ela na tarefa de leitura do APPS e lê ela somente aqui, certo? Nesse caso, o ideal é você usar uma message queue pra passar o dado de uma tarefa pra outra, já que message queue também é um recurso 1:1. Variável global tem uma relação N:N, e é melhor vc deixar o escopo o menor possível pra diminuir problema de coesão.

2022-05-24 22:45 UTC, renanmoreira17 commented on Core/Inc/torque_command/torque_parameters.h
> +// TODO(Felipe): verificar se esse define tá certo
english

2022-05-24 22:45 UTC, renanmoreira17 commented on Core/Inc/torque_command/torque_parameters.h
> +// TODO(Felipe): verificar se esse define tá certo
a partir de hoje português tá banido rs

2022-05-25 00:08 UTC, FelTell commented on Core/Inc/torque_command/torque_parameters.h
> +// TODO(Felipe): verificar se esse define tá certo
ta banido a um tempo, eu que sequelei

2022-05-25 12:48 UTC, FelTell commented on Core/Src/datalogging/speed.c
> +        // Timeout to keep getting inverter speeds even in wheels encoder are stopped.
```suggestion
        // Timeout to keep getting inverter speeds even if wheels encoder are stopped.
```

2022-05-27 18:58 UTC, renanmoreira17 approved these changes

2022-05-27 18:58 UTC, renanmoreira17 commented on Core/Src/sensors/encoder_speed.c
> +                               encoder_int_message_t* last_messages, uint32_t min_count) {
```suggestion
static void reset_speed_single(const encoder_int_message_t* message,
                               const encoder_int_message_t* last_messages, uint32_t min_count) {
```
(vê se ele deixa, aparentemente não deve ser problema)

2022-05-28 18:12 UTC, merged