Ecu3.0/recebimento can geral
Tesla-UFMG/ECU pull request #78
Opened 2022-05-25 21:26 UTC by jp-nunes28

Implementando leitura da can do IMU com a mesma lógica utilizada pela leitura da can do inversor.

2022-05-28 20:02 UTC, FelTell requested changes
Como esse código é de maior parte reaproveitado, os comentários foram mais de nome mesmo. Fica atento que tanto o CubeIDE quanto o VSCode tem funcionalidades que fazem renomeamento em tudo automaticamente, não vá renomear tudo manualmente.

Agora um comentário sobre a estrutura de arquivos que você usou: 
Você n criou nenhum arquivo novo e usou o `CAN_IDs.c/.h`pra fazer a implementação do código que ta implementado no `inverter_can_data_manager.c/.h`. Isso deixa o código despadronizado e dificil de achar o que quer. Tem várias sugestões pra isso e @renanmoreira17 queria que opinasse tbm:

1. Usar `general_can_data_manager.c/.h` e `inverter_can_data_manager.c/.h` e abandonar o `CAN_IDS.c/h`, passando tudo pra que trata a can especifica
2. Usar `general_can_data_manager.c/.h`, `inverter_can_data_manager.c/.h` e `CAN_IDS.h` e abandonar o `CAN_IDS.c`. Assim o `CAN_IDS.h` fica com os defines de ids de todas as cans e apenas isso, enquanto o resto tem as funções de get, set, etc. Essa é a opção que mais gosto
3. Usar apenas um `data_manager.c/.h` que consegue tratar as duas cans

Essa definição vai alterar aquele novo código de envio com x_macros, mas o que decidir aqui vc altera somente o que envolve o recebimento da can geral e do inversor, o envio altera depois com o decidido

2022-05-28 20:08 UTC, FelTell commented
Outra coisa, vi que vc fechou o primerio PR que vc fez, teve algum motivo especial? Só da commit e push que ele atualiza o PR, precisa fechar não.

2022-06-01 23:40 UTC, renanmoreira17 commented
> 2. Usar `general_can_data_manager.c/.h`, `inverter_can_data_manager.c/.h` e `CAN_IDS.h` e abandonar o `CAN_IDS.c`. Assim o `CAN_IDS.h` fica com os defines de ids de todas as cans e apenas isso, enquanto o resto tem as funções de get, set, etc. Essa é a opção que mais gosto

acho essa opção mais robusta também

2022-06-20 02:07 UTC, FelTell commented
Vou olhar depois de resolver o conflito.

2022-06-21 00:39 UTC, FelTell requested changes

2022-06-21 00:39 UTC, FelTell commented on Core/Inc/CAN/general_can_data_manager.h
> +#define INC_GENERAL_CAN_HANDLER_H_
Atualizar o nome disso daqui. Quando vc cria o arquivo pelo cubeide ele ja cria esses defines certos.

```suggestion
#ifndef INC_CAN_GENERAL_CAN_DATA_MANAGER_H_
#define INC_CAN_GENERAL_CAN_DATA_MANAGER_H_
```

2022-06-21 00:39 UTC, FelTell commented on Core/Inc/CAN/general_can_data_manager.h
> +#endif /* INC_CAN_HANDLER_H_ */
atualizar o nome tbm

```suggestion
#endif /* INC_CAN_GENERAL_CAN_DATA_MANAGER_H_ */
```

2022-06-21 00:39 UTC, FelTell commented on Core/Src/dynamic_controls/lateral_control.c
> +    set_global_var_value(GYRO_YAW, general_get_value(gyroscope_y));
Não é assim não. Pode apagar aqui e na linha 29 faz assim:
```
int16_t gyro_yaw = (int16_t) general_get_value(gyroscope_y);
```
Pode apagar a variavel global. E atenção nesse int16_t ai pq ele é importantissimo. A variavel que chega da CAN é unsigned, e vc precisa da esse cast pra signed pra conseguir ler ela corretamente.

2022-06-22 04:17 UTC, FelTell requested changes
sem querer dei push no merge que eu fiz hj de manha pra testar lá no CPH, pode ignorar que ele não fez nada n.

2022-06-22 04:17 UTC, FelTell commented on Core/Src/CAN/general_can_data_manager.c
>   *      Author: renanmoreira
seu nome aqui

2022-06-22 04:17 UTC, FelTell commented on Core/Inc/CAN/general_can_data_manager.h
>   *      Author: renanmoreira
seu nome aqui

2022-06-22 04:17 UTC, FelTell commented on Core/Src/dynamic_controls/lateral_control.c
>      // TODO(renanmoreira): receber GYRO_YAW em algum lugar
```suggestion
```
Apagar TODO

2022-06-22 04:17 UTC, FelTell commented on Core/Src/CAN/inverter_can.c
>          uint32_t idInverter = RxHeader.Identifier;
```suggestion
        uint32_t id= RxHeader.Identifier;
```

2022-06-22 04:17 UTC, FelTell commented on Core/Src/CAN/general_can.c
>          idgeneral = RxHeader.Identifier;
```suggestion
        uint32_t id= RxHeader.Identifier;
```

tira a declaração em cima

2022-06-22 04:17 UTC, FelTell commented on Core/Src/CAN/general_can.c
> +                general_store_value(var_name, data_general);
```suggestion
                uint16_t data= concatenate_two_uint8_to_uint16(RxData + i * 2);
                general_store_value(var_name, data);
```

2022-06-22 13:19 UTC, FelTell approved these changes

2022-06-22 20:30 UTC, merged