Ecu3.0/botao controles dinamicos
Tesla-UFMG/ECU pull request #82
Opened 2022-07-10 02:33 UTC by jp-nunes28

2022-07-22 20:47 UTC, renanmoreira17 requested changes, later dismissed

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/driver_settings/dynamic_controls_choice.c
> +        bool is_RTD_active = get_individual_flag(e_ECU_control_flagsHandle, RTD_FLAG);
acho que vale à pena criar uma função lá no `util` pra isso

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/driver_settings/dynamic_controls_choice.c
> +        }
Não precisa aninhar isso dentro de um bloco de `if`, compromete a legibilidade.
Pensa comigo: esse é o único bloco de código dessa tarefa, e que ele só vai ser executado se não estiver em RTD. Logo, se não tiver em RTD, você pode pedir pra ele “pular” essa iteração da tarefa (percebe ali em cima que o código da tarefa tá em um `for-loop` infinito). Ou seja:
```cpp
        if (!is_RTD_active)
            continue;
            
        bool is_DYNAMIC_CONTROL_active = get_individual_flag(e_ECU_control_flagsHandle, DYNAMIC_CONTROL_FLAG);
        
        ... // (resto do código)
```

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/driver_settings/dynamic_controls_choice.c
> +        	}
melhor fazer um `if-else` aqui

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/torque_command/torque_manager.c
> +        // todo: adicionar novos "if's" quando for implementada a integração dos controles
### NÃO MESMO!!

Melhor usar um switch aqui, semelhante como tava antes. O que eu recomendo você fazer é listar os estados atuais que ele pode alcançar e criar um `enum` com eles. Você cria uma variável pra guardar esse estado aqui nesse mesmo escopo da tarefa, e a definição do estado você faz a partir desses dados que você pegou do `get_gloval_var_value`. **Mas faz isso em uma função!!!** A legibilidade aqui tá muito comprometida

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/torque_command/torque_manager.c
> +            if (is_DYNAMIC_CONTROL_active == true) {
e se estiver desativado? não faz nada? você não encadeou os `if`s (que eu espero que você remova logo logo rs), então não ficou claro que é pra ele fazer a rampa normal em caso de nada ativado

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/torque_command/torque_manager.c
>                  break;
Isso era do switch antigo. Como não tem nenhum outro escopo que aceite `break` aqui além do do `for`, isso vai fazer a tarefa sair da função. Isso faz o RTOS parar de funcionar. De novo, eu espero que você volte isso para um esquema de `switch`, mas cuidado com esse tipo de problema porque é extremamente difícil de debugar (falo por experiência própria rs)

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/torque_command/torque_manager.c
> +            if (is_DYNAMIC_CONTROL_active == true) {
e só mais um detalhe: não precisa comparar coisas `== true`. Isso é essencialmente um “pleonasmo” da programação

2022-07-22 20:47 UTC, renanmoreira17 commented on Core/Src/util/buttons_handler.c
> +        case B_DYNAMICS_CONTROLS:;
acredito que pode tirar esse `;`. Ele era necessário em cima por causa de um bug na linguagem C quando tem declaração de símbolo na frente de definição de label

2022-07-30 23:08 UTC, FelTell requested changes
Achei que ficou bom a lógica, ja fez testes com a ECU física?

2022-07-30 23:08 UTC, FelTell commented on Core/Src/driver_settings/dynamic_controls_choice.c
> +#include "util/util.h"
```suggestion
#include "cmsis_os.h"
#include "util/global_instances.h"
#include "util/global_variables.h"
#include "util/util.h"
```

Sempre tenha apenas os includes necessários. Bom para segurança do código pq limita o escopo a acessar apenas o necessário. Reduz tempo de compilação tbm (eu acho)

2022-07-30 23:08 UTC, FelTell commented on Core/Src/torque_command/torque_manager.c
> +        // controles
todo é em ingles tbm. E coloca seu nome igual ta em outros

2022-07-30 23:08 UTC, FelTell commented on Core/Src/torque_command/torque_manager.c
> +    if (is_DYNAMIC_CONTROL_active) {
cria um TODO aqui tbm pra depois criar o caso dos dois ativos

2022-07-30 23:08 UTC, FelTell commented on Core/Src/torque_command/torque_manager.c
> +#include "driver_settings/dynamic_controls_choice.h"
remover include

2022-07-30 23:09 UTC, FelTell commented on Core/Src/torque_command/torque_manager.c
> +        bool is_DYNAMIC_CONTROL_active =
```suggestion
        const bool is_DYNAMIC_CONTROL_active =
```

2022-08-01 22:25 UTC, jp-nunes28 commented on Core/Inc/torque_command/torque_manager.h
> +// controles
ainda não, vou tentar fazer os testes amanhã.

2022-09-15 16:20 UTC, jp-nunes28 commented on Core/Inc/torque_command/torque_manager.h
> +// controles
Galera fiz o teste aqui no carro e deu certo, o código está funcionando.

2022-09-16 01:48 UTC, FelTell commented
Não vou aprovar por enquanto apenas por que o código da ECU3.0/develop está pronto para ir para a master e não é pra da merge com código que não foi testado com o carro no chão. Porém depois do merge da develop com a master for feito esse código está aprovado.

2022-09-16 10:42 UTC, renanmoreira17 commented
> Não vou aprovar por enquanto apenas por que o código da ECU3.0/develop está pronto para ir para a master e não é pra da merge com código que não foi testado com o carro no chão. Porém depois do merge da develop com a master for feito esse código está aprovado.

Concordo com o Telles. Mais tarde eu vou fazer uma revisão final também.

2023-02-28 14:13 UTC, dmrohrs commented on Core/Src/main.c
>  /* USER CODE BEGIN Header */
O main.c foi formatado com o clang-format. Por ser um código gerado pelo Cube é melhor deixar com a formatação original

2023-02-28 14:16 UTC, dmrohrs requested changes
Pelo que entendi, o botão de controles dinâmicos vai ativar o controle que é configurado pra cada modo. Por exemplo, se no modo de aceleração o controle configurado no initializers.c for 
traction_control, o controle de arrancada é que vai ser utilizado no carro. Por que foi pensada a lógica desse jeito? Vcs não gostam da ideia de um botão sequencial que muda entre VT e CA e uma forma de mostrar isso no Nextion? Ou preferem que o tipo de controle fique ligado ao modo mesmo

2023-02-28 23:26 UTC, FelTell approved these changes

2023-03-01 17:04 UTC, dmrohrs approved these changes

2023-03-02 17:34 UTC, merged