Ecu3.0/xmacro
Tesla-UFMG/ECU pull request #83
Opened 2022-07-12 23:51 UTC by tarcisiolucas

Implementada xmacro nos ids de CAN da datalogger

2022-07-15 00:27 UTC, luizaaraujo1 requested changes, later dismissed

2022-07-15 01:44 UTC, tarcisiolucas commented on Core/Src/datalogging/datalogger.c
> +extern datalog_send_t datalog_send_struct[QUANT_RESERVED_ID + 1];
Quando preenche os ids na estrutura de envio tem uma comparação com a posição a frente pra saber se tem que iterar a posição da estrutura ou não:
```
if (CAN_ID_map[pos_ord].id != CAN_ID_map[pos_ord + 1].id) {
            datalog_send_struct[pos_struct].extern_ID = CAN_ID_map[pos_ord].id;
            pos_struct++;
}
```
mas quando chega no final ele faz a comparação com uma posição que não existe gerando um warning, então pra não ocorrer eu coloquei mais uma posição com o id 0 que não é utilizado

2022-07-15 02:04 UTC, tarcisiolucas commented on Core/Src/CAN/CAN_IDs.c
> +            pos_struct++;
assim fica mais compreensível?
`int i = 0;
    for (int j = 0; j < CAN_ID_QUAN; j++) {
        // puts the internal id "CAN_ID_map[j].var" in the vector using its corresponding
        // position CAN_ID_map[j].pos
        datalog_send_struct[i].pos[CAN_ID_map[j].pos] = CAN_ID_map[j].var;
        if (CAN_ID_map[j].id != CAN_ID_map[j + 1].id) {
            datalog_send_struct[i].extern_ID = CAN_ID_map[j].id;
            i++;
        }
    }`

2022-07-15 02:05 UTC, tarcisiolucas commented on Core/Src/CAN/CAN_IDs.c
> +            pos_struct++;
assim fica mais compreensível?
```
int i = 0;
    for (int j = 0; j < CAN_ID_QUAN; j++) {
        // puts the internal id "CAN_ID_map[j].var" in the vector using its corresponding
        // position CAN_ID_map[j].pos
        datalog_send_struct[i].pos[CAN_ID_map[j].pos] = CAN_ID_map[j].var;
        if (CAN_ID_map[j].id != CAN_ID_map[j + 1].id) {
            datalog_send_struct[i].extern_ID = CAN_ID_map[j].id;
            i++;
        }
    }
```

2022-07-15 10:13 UTC, luizaaraujo1 commented on Core/Src/CAN/CAN_IDs.c
> +            pos_struct++;
Sim!

2022-07-15 10:45 UTC, luizaaraujo1 commented on Core/Src/datalogging/datalogger.c
> +extern datalog_send_t datalog_send_struct[QUANT_RESERVED_ID + 1];
Entendi. Eu acho que existem maneiras mais robustas de fazer isso, por exemplo algo nesse sentido:
`int pos_struct = 0;
 int pos_ord = 0;
 datalog_send_struct[pos_struct].pos[CAN_ID_map[pos_ord].pos] = CAN_ID_map[pos_ord].var;
 datalog_send_struct[pos_struct].extern_ID = CAN_ID_map[pos_ord].id;
 for (pos_ord = 1; pos_ord < CAN_ID_QUAN; pos_ord++) {
     if (CAN_ID_map[pos_ord].id != CAN_ID_map[pos_ord - 1].id) {
            pos_struct++;
            datalog_send_struct[pos_struct].extern_ID = CAN_ID_map[pos_ord].id;
         }
     datalog_send_struct[pos_struct].pos[CAN_ID_map[pos_ord].pos] = CAN_ID_map[pos_ord].var;
     }`

Só tomar cuidado pra não mandar algum dado na pos_struct errada

2022-07-15 10:51 UTC, luizaaraujo1 commented on Core/Src/datalogging/datalogger.c
> +extern datalog_send_t datalog_send_struct[QUANT_RESERVED_ID + 1];
Entendi. Eu acho que existem maneiras mais robustas de fazer isso, por exemplo algo nesse sentido:

 ```int pos_struct = 0;
 int pos_ord = 0;
 datalog_send_struct[pos_struct].pos[CAN_ID_map[pos_ord].pos] = CAN_ID_map[pos_ord].var;
 datalog_send_struct[pos_struct].extern_ID = CAN_ID_map[pos_ord].id;
 for (pos_ord = 1; pos_ord < CAN_ID_QUAN; pos_ord++) {
     if (CAN_ID_map[pos_ord].id != CAN_ID_map[pos_ord - 1].id) {
            pos_struct++;
            datalog_send_struct[pos_struct].extern_ID = CAN_ID_map[pos_ord].id;
      }
     datalog_send_struct[pos_struct].pos[CAN_ID_map[pos_ord].pos] = CAN_ID_map[pos_ord].var;
}
```
Só tomar cuidado pra não mandar algum dado na pos_struct errada.

2022-07-18 00:09 UTC, FelTell requested changes
Vamos marcar uma reunião pra alinhar umas lógicas que eu acho que podem ser melhoradas. Enquanto isso da pra corrigir essas mudanças ai.

Atenção pro nome da branch. xmacro é um péssimo nome, nada descritivo, datalog-xmacro ja seria melhor. Pelo que vi foi o @dmrohrs que criou a branch, então vamos ter cuidado com isso da próxima vez.

2022-07-20 22:30 UTC, tarcisiolucas commented on Core/Src/CAN/CAN_IDs.c
> +datalog_send_t datalog_send_struct[QUANT_RESERVED_ID];
Porque o tamanho da estrutura é a quantidade de ids externos sem contar as words, se eu colocar o tamanho do CAN_ID_QUAN vai ser a quantidade de words utilizadas e a estrutura pode ficar muito grande

2022-07-20 23:33 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +        for (uint16_t j = i + 1; j < CAN_ID_QUAN; j++) {
Coloca no define um cast para (uint16_t) pra limitar o tamanho do define

2022-07-22 21:26 UTC, renanmoreira17 requested changes

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Inc/CAN/CAN_IDs.h
> +    uint16_t extern_ID;
external

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/CAN/CAN_IDs.c
> +    // position "CAN_ID_map[j].pos"
esse comentário tá dizendo exatamente o que você fez na linha abaixo (ou seja, ele é inútil). Melhor você comentar, de forma geral, o que essa pretende fazer quando ela terminar de ser computada

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/CAN/CAN_IDs.c
>      }
Você não precisa de criar uma iteração separada pra isso.
```cpp
int last_id = -1;
for (j = 0; j < (uint16_t)CAN_ID_QUAN; j++) {
  auto current_CAN_ID_map = CAN_ID_map[j];
  auto current_id = current_CAN_ID_map.id;
  if (current_id != last_id) {
       datalog_send_struct[i].extern_ID = current_id;
       i++;
   }
   datalog_send_struct[i].pos[current_CAN_ID_map.pos] = current_CAN_ID_map.var;
   last_id = current_id;
}
```

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/CAN/CAN_IDs.c
>      }
e pra falar a verdade, eu acharia mais interessante se você populasse esse vetor por struct pronta. Ou seja: você iteraria sobre o `CAN_ID_map` e montaria a struct até que o ID mude. Assim que o ID mudar, você pegaria essa struct que você tava construindo e assinalaria ela na `datalog_send_struct`. Fica mais organizado e menos suscetível a erro do que montar ela aos pouco igual tá sendo feito aqui. Mas se você achar muito trampo, pode deixar assim mesmoó, s deixa um `TODO` pra lembrar de lidar com isso depois

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/datalogging/datalogger.c
> +        for (uint16_t struct_pos = 1; struct_pos < get_amount_ext_id(); struct_pos++) {
por que a partir de 1?

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/datalogging/datalogger.c
> +                }
```suggestion
                vet_tx[word] = (internal_id != -1) ? datalog_data_holder[internal_id] : 0;
```

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/datalogging/datalogger.c
> +        // extract again
pode remover esse comentário

2022-07-22 21:26 UTC, renanmoreira17 commented on Core/Src/datalogging/datalogger.c
> +            // transmit data via CAN
pode remover esse comentário

2022-07-22 21:28 UTC, renanmoreira17 commented
@tarcisiolucas eu tinha começado a fazer o review um tempo atrás, então alguns comentários podem apontar coisas que tão desatualizadas. Se for o caso, tenta adaptar o que eu falei pra versão nova, ou desconsidera dependendo

2023-02-08 23:53 UTC, tarcisiolucas commented on Core/Src/datalogging/datalogger.c
> +        for (uint16_t struct_pos = 1; struct_pos < get_amount_ext_id(); struct_pos++) {
o 0 era uma ID reservada então eu não estava enviando

2023-02-09 12:23 UTC, renanmoreira17 submitted a review, later dismissed
Faz um merge da **develop** pra esse branch, e troca o destino do pull request pra **develop**. Não é pra utilizar os `ECU3.0/*` mais

2023-03-03 12:19 UTC, FelTell requested changes

2023-03-03 12:19 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +static int compare_function(const void* value1, const void* value2) {
compare_function é um nome genérico, essa função só compara o CAN_var_inf, muda ou nome para compare_CAN_var_info() ou algo assim.

2023-03-03 12:19 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +    }
Para ficar menos verboso:
```suggestion
    const uint16_t first_id  = ((CAN_var_inf*)value1)->id;
    const uint16_t second_id = ((CAN_var_inf*)value2)->id;
    if (first_id < second_id) {
        return -1;
    }
    if (first_id > second_id) {
        return 1;
    }
```
E msm coisa para o pos

2023-03-03 12:19 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +    qsort(CAN_ID_map, CAN_GENERAL_ID_QUAN, sizeof(CAN_var_inf), compare_function);
Top

2023-03-03 12:19 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +    CAN_ID_map[var_name].var = var_name;                                                 \
Esse `CAN_ID_map[var_name].var = var_name;` é redudante, já que ele é igual o próprio index do array.
O único lugar que achei que usa esse .var foi esse: `aux_datalog_struct.pos[CAN_ID_map[i].pos] = CAN_ID_map[i].var;`. Acho pode tirar o .var da struct e ai ficaria assim: `aux_datalog_struct.pos[CAN_ID_map[i].pos] = i;`

2023-03-03 12:19 UTC, FelTell commented on Core/Inc/CAN/CAN_IDs.h
> +} datalog_send_t;
Nesse pos fica o id da mensagem que vai ser enviada, certo? Se sim, deixa isso mais claro.
```suggestion
typedef struct {
    uint16_t external_ID;
    CAN_general_list_e message_to_send[4];
} datalog_send_t;
```

2023-03-03 12:19 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +static int compare_function();
Não deixe o protótipo vazio. Pq deixar vazio significa que a função pode ter nenhum argumento ou todos os argumentos. O correto é sempre colocar, até quando tiver nenhum argumento o certo é colocar (void), mas não esquenta com isso por agr. 

```suggestion
static int compare_function(const void* value1, const void* value2);
```

2023-03-03 12:19 UTC, FelTell commented on Core/Src/CAN/CAN_IDs.c
> +        for (uint16_t k = 0; k < 4; k++) {
tentar sempre criar define pra numeros
```suggestion
        for (uint16_t k = 0; k < WORDS_PER_ID; k++) {
```

2023-03-13 11:55 UTC, renanmoreira17 commented
Vou revisar isso aqui rsrs tenham só um pouco de paciência

2023-04-29 22:19 UTC, FelTell approved these changes

2023-05-16 16:38 UTC, dmrohrs approved these changes

2023-05-16 16:42 UTC, merged